### ISSUE TITLE
Can not download data

### ISSUE THREAD

**Issue by undcloud** [CVMI-Lab/UHDM#2]
Hi, I have failed to download train.tar.gz many times, so do my workmate.     
Could you chop your big file into small files?  
Which license  used here?  
Thank you

**Comment by XinYu-Andy** [comment]
1. How did you download the dataset? Use bash script or directly download from google drive?
2. The code and dataset can be only used for research purpose currently.

**Comment by undcloud** [comment]
1. I used both means
2. OK

**Comment by XinYu-Andy** [comment]
So what's the error reported? Just caused by the large size?


> 1. I used both means
> 2. OK

**Comment by undcloud** [comment]
> So what's the error reported? Just caused by the large size?
> 
> > 1. I used both means
> > 2. OK

gdown https://drive.google.com/uc?id=1NiTohc65FZZXvmFpI80OTczp5Vc6EGDe
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Anaconda\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "D:\Anaconda\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\Anaconda\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "D:\Anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000014BB1E02CA0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\Anaconda\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1NiTohc65FZZXvmFpI80OTczp5Vc6EGDe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014BB1E02CA0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有 反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\Scripts\gdown.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda\lib\site-packages\gdown\cli.py", line 156, in main
    filename = download(
  File "D:\Anaconda\lib\site-packages\gdown\download.py", line 146, in download
    res = sess.get(url, headers=headers, stream=True, verify=verify)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1NiTohc65FZZXvmFpI80OTczp5Vc6EGDe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014BB1E02CA0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by undcloud** [comment]
When I download file from google drive,  breakdown half the way.

> So what's the error reported? Just caused by the large size?
> 
> > 1. I used both means
> > 2. OK

**Comment by XinYu-Andy** [comment]
I am not sure what the problem is here. 
But anyway, I will later chop the big file into small files and provide the link.  

> When I download file from google drive, breakdown half the way.
> 
> > So what's the error reported? Just caused by the large size?
> > > 1. I used both means
> > > 2. OK

**Comment by undcloud** [comment]
> I am not sure what the problem is here. But anyway, I will later chop the big file into small files and provide the link.
> 
> > When I download file from google drive, breakdown half the way.
> > > So what's the error reported? Just caused by the large size?
> > > > 1. I used both means
> > > > 2. OK

OK, wish I can use them in the later.  ~v~

**Comment by undcloud** [comment]
Hello, sorry for late reply ,  I can download train_split00.tar.gz.  
We will obey the license, if you changed the license, please let me know, it is a goog work, high resolution's work is very rare,  thank you ~
